### ISSUE TITLE
autoconfig error

### ISSUE THREAD

**Issue by marozsas** [ojrdevcom/shafs#1]
Hi !
I got interrested on this but I was unable to figure out why autoconfig issues the following error:

```
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:4: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
```
My system: opensuse tumbleweed with devel meta package installed.

**Comment by ojrdevcom** [comment]
The build instructions were incorrect. Sorry about that. I've pushed a new README.

Please let me know if you're able to build it now.

**Comment by marozsas** [comment]
Not yet...
`
automake --add-missing
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:6: error: required file 'config.h.in' not found
Makefile.am: installing './depcomp'
/usr/share/automake-1.16/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.16/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.16/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.16/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.16/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.16/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
`

**Comment by ojrdevcom** [comment]
Try again now please?

**Comment by marozsas** [comment]
Exactly the same message.
I've removed and downloaded again from github.
I am sure I have sqlite3 and sqilte3-devel installed.

**Comment by ojrdevcom** [comment]
Oh you can safely ignore those. Proceed to next step in build and it should work fine.

I'll check why it's printing that.

**Comment by marozsas** [comment]
OK, right.
Looks like it compiled although with some warnings; anyway...

```
make
make  all-am
make[1]: Entering directory '/home/miguel/src/shafs'
gcc -DHAVE_CONFIG_H -I.    -Wall -pedantic -g -O2 -MT shafs-shafs.o -MD -MP -MF .deps/shafs-shafs.Tpo -c -o shafs-shafs.o `test -f 'shafs.c' || echo './'`shafs.c
shafs.c: In function ‘shafs_walk_dir’:
shafs.c:170:13: warning: ‘strncat’ specified bound 1 equals source length [-Wstringop-overflow=]
  170 |             strncat(newf, "/", 1);
      |             ^~~~~~~~~~~~~~~~~~~~~
shafs.c: In function ‘shafs_walk_dir.part.0’:
shafs.c:168:9: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  168 |         strncat(newf, fil, strlen(fil));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shafs.c:172:9: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  172 |         strncat(newf, dent->d_name, strlen(dent->d_name));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ojrdevcom** [comment]
Can you post the output of `gcc --version` please?

**Comment by marozsas** [comment]
> Can you post the output of `gcc --version` please?

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go,d --enable-offload-targets=nvptx-none=/usr/nvptx-none,amdgcn-amdhsa=/usr/amdgcn-amdhsa, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/10 --enable-ssp --disable-libssp --disable-libvtv --enable-cet=auto --disable-libcc1 --enable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-libphobos --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-10 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --with-build-config=bootstrap-lto-lean --enable-link-mutex --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201117 [revision 98ba03ffe0b9f37b4916ce6238fad754e00d720b] (SUSE Linux) 
```

**Comment by ojrdevcom** [comment]
Ah! GCC 10. Haven't tested it yet. Thanks for that.

I've made some recent fixes, can you please retry?

**Comment by marozsas** [comment]
Yes, thank you. No issues this time.

**Comment by ojrdevcom** [comment]
Thank you for raising this issue and helping me debug it. 

I'm closing this report for now.
